var allResult = {
    "mode": "all",
    "tests": [
        { "number": "1a", "name": "Bayesian network diagram", "description": "Bayesian network diagram", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "1b", "name": "joint probability expression", "description": "joint probability expression", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "1c", "name": "marginal probability p(WetGrass)", "description": "marginal probability p(WetGrass)", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "1d", "name": "likelihood calculation", "description": "likelihood calculation", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "1e", "name": "independence analysis", "description": "independence analysis", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "2a-0-basic", "name": "Phylogenetic tree initialization", "description": "Test phylogenetic tree initialization with mutation rate", "max_seconds": 1, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "2a-1-basic", "name": "Mutation model CPT check", "description": "Test mutation model CPT with various mutation rates", "max_seconds": 1, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "2b-0-basic", "name": "Forward sampling validity", "description": "Ensure forward_sampling returns valid assignments", "max_seconds": 1, "max_points": 5, "extra_credit": false, "basic": true },
        { "number": "2c-0-basic", "name": "Test compute_joint_probability", "description": "Test compute_joint_probability", "max_seconds": 1, "max_points": 5, "extra_credit": false, "basic": true },
        { "number": "2d", "name": "Table of sampled values", "description": "Table of sampled values", "max_seconds": null, "max_points": 1, "extra_credit": false, "basic": false },
        { "number": "2e", "name": "Rejection sampling implementation", "description": "Rejection sampling implementation", "max_seconds": 1, "max_points": 3, "extra_credit": false, "basic": true },
        { "number": "2f", "name": "Gibbs sampling implementation", "description": "Gibbs sampling implementation", "max_seconds": 1, "max_points": 5, "extra_credit": false, "basic": true },
        { "number": "2g", "name": "Sampling comparison writeup", "description": "Compare rejection and Gibbs sampling posterior estimates", "max_seconds": null, "max_points": 4, "extra_credit": false, "basic": false },
        { "number": "3a", "name": "Bayesian network diagram for annotators", "description": "Bayesian network diagram for annotators", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "3b", "name": "Perfect annotator CPT", "description": "Specify the CPT for a perfect annotator", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "3c", "name": "Random annotator CPT", "description": "Specify the CPT for a random-guessing annotator", "max_seconds": null, "max_points": 1, "extra_credit": false, "basic": false },
        { "number": "3d-0-basic", "name": "Annotator network structure", "description": "Annotator network structure", "max_seconds": 1, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "3d-1-basic", "name": "Annotator CPT diagonal dominance", "description": "Annotator CPT diagonal dominance", "max_seconds": 1, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "3d-2-hidden", "name": "Hidden annotator network counts", "description": "Hidden annotator network counts", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "3e-0-basic", "name": "accumulate_assignment counting", "description": "accumulate_assignment counting", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "3e-1-basic", "name": "mle_estimate parameter learning (no smoothing)", "description": "Check MLE parameter updates without smoothing", "max_seconds": 1, "max_points": 3, "extra_credit": false, "basic": true },
        { "number": "3e-2-basic", "name": "mle_estimate parameter learning (smoothing)", "description": "Check MLE parameter updates with smoothing", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "3f", "name": "MLE for annotators", "description": "MLE for annotators", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "3f-hidden", "name": "Hidden MLE for annotators", "description": "MLE for annotators with random data", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "3g", "name": "Annotator reliability analysis", "description": "Interpret annotator CPT plots after MLE training", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "4a-0-basic", "name": "Expectation step counts", "description": "Ensure e_step matches direct counts for fully observed data", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "4a-1-basic", "name": "Expectation step normalization", "description": "Verify e_step normalizes weights when labels are hidden", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "4a-2-basic", "name": "Expectation step multi-hidden", "description": "Check e_step with multiple hidden annotators", "max_seconds": 1, "max_points": 3, "extra_credit": false, "basic": true },
        { "number": "4a-3-hidden", "name": "Hidden e_step randomised checks", "description": "Hidden e_step randomised checks", "max_seconds": 1, "max_points": 3, "extra_credit": false, "basic": false },
        { "number": "4b-0-basic", "name": "Maximization step update", "description": "Check m_step with weighted completions", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "4b-1-basic", "name": "Maximization step multi-case", "description": "Check m_step with multiple weighted completions", "max_seconds": 1, "max_points": 3, "extra_credit": false, "basic": true },
        { "number": "4b-2-hidden", "name": "Hidden m_step randomised checks", "description": "Hidden m_step randomised checks", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "4c-0-basic", "name": "EM convergence on hidden labels", "description": "EM convergence on hidden labels", "max_seconds": 1, "max_points": 3, "extra_credit": false, "basic": true },
        { "number": "4c-1-basic", "name": "EM updates from random init", "description": "EM updates from random init", "max_seconds": 1, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "4d", "name": "Annotator CPT plots", "description": "Plot annotator CPTs after 100 EM iterations", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "4e", "name": "EM recovery analysis", "description": "Explain whether EM recovered the true labels using the plots", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false }
    ],
    "leaderboard": []
};
