var allResult = {
    "mode": "all",
    "tests": [
        { "number": "1a", "name": "feature representation", "description": "feature representation", "max_seconds": null, "max_points": 1, "extra_credit": false, "basic": false },
        { "number": "1b", "name": "softmax computation", "description": "softmax computation", "max_seconds": null, "max_points": 1, "extra_credit": false, "basic": false },
        { "number": "1c", "name": "cross-entropy loss", "description": "cross-entropy loss", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "1d", "name": "gradient analysis", "description": "gradient analysis", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "2a", "name": "embeddings via averaging", "description": "embeddings via averaging", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "2b", "name": "forward pass", "description": "forward pass", "max_seconds": null, "max_points": 3, "extra_credit": false, "basic": false },
        { "number": "2c", "name": "backpropagation", "description": "backward pass", "max_seconds": null, "max_points": 3, "extra_credit": false, "basic": false },
        { "number": "2d", "name": "embedding analysis", "description": "embedding analysis", "max_seconds": null, "max_points": 2, "extra_credit": false, "basic": false },
        { "number": "3a-0-basic", "name": "vocabulary building test", "description": "vocabulary building test", "max_seconds": 1, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "3b-0-basic", "name": "NumPy SGD basic test", "description": "NumPy SGD basic test", "max_seconds": 2, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "3c-0-basic", "name": "numpy softmax test", "description": "numpy softmax test", "max_seconds": 2, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "3d-0-basic", "name": "numpy cross entropy loss test", "description": "numpy cross entropy loss test", "max_seconds": 2, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "3e-0-basic", "name": "numpy compute gradients test", "description": "numpy compute gradients test", "max_seconds": 2, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "3f-0-basic", "name": "predict linear classifier test", "description": "predict linear classifier test", "max_seconds": 2, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "3g-0-basic", "name": "train linear classifier basic test", "description": "train linear classifier basic test", "max_seconds": 5, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "3g-1-hidden", "name": "train linear classifier gradient test", "description": "train linear classifier gradient test", "max_seconds": 5, "max_points": 1, "extra_credit": false, "basic": false },
        { "number": "3g-2-basic", "name": "test NumPy implementation on real tweet data", "description": "test NumPy implementation on real tweet data", "max_seconds": 30, "max_points": 3, "extra_credit": false, "basic": true },
        { "number": "3h", "name": "exploring learning rates", "description": "exploring learning rates", "max_seconds": null, "max_points": 3, "extra_credit": false, "basic": false },
        { "number": "4a-0-basic", "name": "text to average embedding test", "description": "text to average embedding test", "max_seconds": 2, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "4b-0-basic", "name": "extract averaged features test", "description": "extract averaged features test", "max_seconds": 2, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "4c-0-basic", "name": "MLP classifier test", "description": "MLP classifier test", "max_seconds": 2, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "4d-0-basic", "name": "torch utility functions test", "description": "torch utility functions test", "max_seconds": 3, "max_points": 3, "extra_credit": false, "basic": true },
        { "number": "4e-0-basic", "name": "predict MLP test", "description": "predict MLP test", "max_seconds": 3, "max_points": 2, "extra_credit": false, "basic": true },
        { "number": "4f-0-basic", "name": "train embedding MLP classifier basic test", "description": "train embedding MLP classifier basic test", "max_seconds": 10, "max_points": 1, "extra_credit": false, "basic": true },
        { "number": "4f-1-hidden", "name": "train embedding MLP classifier shape test", "description": "train embedding MLP classifier shape test", "max_seconds": 8, "max_points": 1, "extra_credit": false, "basic": false },
        { "number": "4f-2-basic", "name": "test PyTorch embedding implementation on real tweet data", "description": "test PyTorch embedding implementation on real tweet data", "max_seconds": 40, "max_points": 3, "extra_credit": false, "basic": true },
    ],
    "leaderboard": [] };
